name: flutter_dialog
description: >-
  Flutter package to show beautiful dialogs with animations as simply as possible (from flutter).
version: 1.0.0
homepage: https://github.com/ali-star/FlutterDialog

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^2.5.1
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - assets/flare/
